apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: run-test-on-client-task-run
spec:
  serviceAccountName: testing-service
  inputs:
    resources:
      - name: git-repo-shopping-list
        resourceRef:
          name: git-repo-shopping-list
  taskRef:
    name: run-test-on-client